
version: '3.4'

services:
  icecream.web:
    container_name: icecream-web
    image: ${DOCKER_REGISTRY-}icecreamweb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:80"